### ISSUE TITLE
Jupyter: unknown type name 'GLIBCXX_BEGIN_NAMESPACE_VERSION'

### ISSUE THREAD

**Issue by vroomanj** [root-mirror/cling#12]
I installed cling using the Scientific Linux binary in CentOS 7 and I am getting the following error in my Jupyter Notebook when I try a simple include. Does anyone have any ideas what might be the cause? Am I missing an environmental variable of some sort? I have glibc-devel and glibc-devel.i686 installed. Any help would be greatly appreciated, thanks!

> In file included from input_line_3:1:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iostream:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ostream:38:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ios:38:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iosfwd:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:40:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:52:1: error: unknown type name '_GLIBCXX_BEGIN_NAMESPACE_VERSION'
_GLIBCXX_BEGIN_NAMESPACE_VERSION
^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:63:3: error: expected unqualified-id
  template<typename>
  ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:67:11: error: explicit specialization of non-template class 'allocator'
    class allocator<void>;
          ^        ~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:75:1: error: unknown type name '_GLIBCXX_END_NAMESPACE_VERSION'
_GLIBCXX_END_NAMESPACE_VERSION
^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/memoryfwd.h:76:1: error: expected unqualified-id
} // namespace std
^
In file included from input_line_3:1:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iostream:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ostream:38:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ios:38:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iosfwd:39:
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:44:1: error: unknown type name '_GLIBCXX_BEGIN_NAMESPACE_VERSION'
_GLIBCXX_BEGIN_NAMESPACE_VERSION
^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:52:3: error: expected unqualified-id
  template<class _CharT>
  ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:55:48: error: unknown type name 'char_traits'
  template<typename _CharT, typename _Traits = char_traits<_CharT>,
                                               ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:55:59: error: expected ',' or '>' in template-parameter-list
  template<typename _CharT, typename _Traits = char_traits<_CharT>,
                                                          ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:55:67: error: expected unqualified-id
  template<typename _CharT, typename _Traits = char_traits<_CharT>,
                                                                  ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:59:21: error: explicit specialization of non-template struct 'char_traits'
  template<> struct char_traits<char>;
                    ^          ~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:62:11: error: unknown type name 'basic_string'
  typedef basic_string<char>    string;   
          ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:62:23: error: expected unqualified-id
  typedef basic_string<char>    string;   
                      ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:65:21: error: explicit specialization of non-template struct 'char_traits'
  template<> struct char_traits<wchar_t>;
                    ^          ~~~~~~~~~
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:68:11: error: unknown type name 'basic_string'
  typedef basic_string<wchar_t> wstring;   
          ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:68:23: error: expected unqualified-id
  typedef basic_string<wchar_t> wstring;   
                      ^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:86:1: error: unknown type name '_GLIBCXX_END_NAMESPACE_VERSION'
_GLIBCXX_END_NAMESPACE_VERSION
^
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/stringfwd.h:87:1: error: expected unqualified-id
} // namespace std
^
In file included from input_line_3:1:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iostream:39:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ostream:38:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/ios:38:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/iosfwd:40:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/postypes.h:40:
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/cwchar:44:
In file included from /usr/include/wchar.h:51:
/opt/lib/clang/3.7.0/include/stddef.h:62:9: error: unknown type name '__SIZE_TYPE__'
typedef __SIZE_TYPE__ size_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by karies** [comment]
Hi,

Did you download the slc6 binary or a cc7 binary of cling? The latter might work. The former likely not. It's probably best if you build cling yourself.

I'm on a trip, please don't expect quick turnarounds for the moment...

Cheers, Axel

**Comment by vroomanj** [comment]
I used cc7 binaries. Cling itself works from the command line. Does this
prove anything useful?

The problem with building it myself is I'm trying to get this working in a
Docker container like I have with other Jupyter kernels.

**Comment by karies** [comment]
If cling works then indeed Jupyter should work, too! Very strange, especially as this is not the first file that gets parsed. Before your #include, can you execute the meta-command ".files" and post the output?

**Comment by vroomanj** [comment]
I'm afraid I don't get anything exciting executing .files:

> input_line_3:2:2: error: expected expression
 .files
 ^

**Comment by vroomanj** [comment]
Additionally, I attempted to compile from my Dockerfile but ended up with the following CMake error:

> CMake Error at tools/cling/cmake_install.cmake:36 (FILE):
  file INSTALL cannot copy file
  "/src/tools/cling/include/cling/Interpreter/CValuePrinter.h" to
  "/opt/cling/include/cling/Interpreter/CValuePrinter.h".
Call Stack (most recent call first):
  tools/cmake_install.cmake:75 (INCLUDE)
  cmake_install.cmake:61 (INCLUDE)


make: *** [install] Error 1

**Comment by karies** [comment]
Sorry - `.files` is only there since two weeks or so. Could you try again, please?

I have never tried to compile from a Dockerfile; looks like a permission issue. I don't think I want to debug this as this does not really seem to be cling related. So let's focus on the original failure!

**Comment by vroomanj** [comment]
I was able to get cling to compile in a Dockerfile and everything works
fine that way. Do you want to debug the original issue or consider this
resolved?

**Comment by karies** [comment]
I have never seen this issue before so maybe we wait until it resurfaces. Thanks for your feedback!

(And in a few weeks I'll make sure that the binaries work also for Jupyter. There is already another open issue on this.)

**Comment by balta2ar** [comment]
@karies Is Ubuntu 12 supported? I've tried compiling from source, but I get this error:
```
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:93:43: error: invalid use of incomplete type ‘class textinput::TabCompletion’
   class TabCompletion : public textinput::TabCompletion {
                                           ^
In file included from /home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:15:0:
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/textinput/TextInput.h:30:9: error: forward declaration of ‘class textinput::TabCompletion’
   class TabCompletion;
         ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:94:11: error: ‘Interpreter’ does not name a type
     const Interpreter& m_ParentInterpreter;
           ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:97:25: error: ‘Interpreter’ does not name a type
     TabCompletion(const Interpreter& Parent) : m_ParentInterpreter(Parent) {}
                         ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:100:10: error: ‘bool {anonymous}::TabCompletion::Complete(textinput::Text&, size_t&, textinp
ut::EditorRange&, std::vector<std::basic_string<char> >&)’ marked override, but does not override
     bool Complete(textinput::Text& Line /*in+out*/,
          ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp: In constructor ‘{anonymous}::TabCompletion::TabCompletion(const int&)’:
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:97:48: error: class ‘{anonymous}::TabCompletion’ does not have any field named ‘m_ParentInte
rpreter’
     TabCompletion(const Interpreter& Parent) : m_ParentInterpreter(Parent) {}
                                                ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp: In member function ‘bool {anonymous}::TabCompletion::Complete(textinput::Text&, size_t&, te
xtinput::EditorRange&, std::vector<std::basic_string<char> >&)’:
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:104:7: error: ‘m_ParentInterpreter’ was not declared in this scope
       m_ParentInterpreter->codeComplete(Line.GetText(), Cursor, Completions);
       ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:105:5: warning: no return statement in function returning non-void [-Wreturn-type]
     }
     ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp: In member function ‘void cling::UserInterface::runInteractively(bool)’:
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:144:5: error: reference to ‘TabCompletion’ is ambiguous
     TabCompletion* Completion =
     ^
In file included from /home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:15:0:
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/textinput/TextInput.h:30:9: note: candidates are: class textinput::TabCompletion
   class TabCompletion;
         ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:93:9: note:                 class {anonymous}::TabCompletion
   class TabCompletion : public textinput::TabCompletion {
         ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:144:20: error: ‘Completion’ was not declared in this scope
     TabCompletion* Completion =
                    ^
/home/ybochkarev/tmp/hy/cling/src/tools/cling/lib/UserInterface/UserInterface.cpp:145:23: error: expected type-specifier
                   new cling::TabCompletion(m_MetaProcessor->getInterpreter());
```

Then I tried using binaries: cling_2016-07-17_ubuntu14. This is probably silly to use binaries for Ubuntu14 on Ubuntu12. Anyway, I proceeded and got this error:

```

In file included from input_line_3:1:
In file included from /usr/include/c++/4.9/iostream:39:
In file included from /usr/include/c++/4.9/ostream:38:
In file included from /usr/include/c++/4.9/ios:38:
In file included from /usr/include/c++/4.9/iosfwd:39:
In file included from /usr/include/c++/4.9/bits/stringfwd.h:40:
/usr/include/c++/4.9/bits/memoryfwd.h:52:1: error: unknown type name '_GLIBCXX_BEGIN_NAMESPACE_VERSION'
_GLIBCXX_BEGIN_NAMESPACE_VERSION
^
/usr/include/c++/4.9/bits/memoryfwd.h:63:3: error: expected unqualified-id
  template<typename>
  ^
/usr/include/c++/4.9/bits/memoryfwd.h:67:11: error: explicit specialization of non-template class 'allocator'
    class allocator<void>;
          ^        ~~~~~~
/usr/include/c++/4.9/bits/memoryfwd.h:75:1: error: unknown type name '_GLIBCXX_END_NAMESPACE_VERSION'
_GLIBCXX_END_NAMESPACE_VERSION
^
/usr/include/c++/4.9/bits/memoryfwd.h:76:1: error: expected unqualified-id
} // namespace std
^
In file included from input_line_3:1:
In file included from /usr/include/c++/4.9/iostream:39:
In file included from /usr/include/c++/4.9/ostream:38:
In file included from /usr/include/c++/4.9/ios:38:
In file included from /usr/include/c++/4.9/iosfwd:39:
/usr/include/c++/4.9/bits/stringfwd.h:44:1: error: unknown type name '_GLIBCXX_BEGIN_NAMESPACE_VERSION'
_GLIBCXX_BEGIN_NAMESPACE_VERSION
^
/usr/include/c++/4.9/bits/stringfwd.h:52:3: error: expected unqualified-id
  template<class _CharT>
  ^
/usr/include/c++/4.9/bits/stringfwd.h:55:48: error: unknown type name 'char_traits'
  template<typename _CharT, typename _Traits = char_traits<_CharT>,
                                               ^
/usr/include/c++/4.9/bits/stringfwd.h:55:59: error: expected ',' or '>' in template-parameter-list
  template<typename _CharT, typename _Traits = char_traits<_CharT>,
                                                          ^
/usr/include/c++/4.9/bits/stringfwd.h:55:67: error: expected unqualified-id
  template<typename _CharT, typename _Traits = char_traits<_CharT>,
                                                                  ^
/usr/include/c++/4.9/bits/stringfwd.h:59:21: error: explicit specialization of non-template struct 'char_traits'
  template<> struct char_traits<char>;
                    ^          ~~~~~~
/usr/include/c++/4.9/bits/stringfwd.h:62:11: error: unknown type name 'basic_string'
  typedef basic_string<char>    string;   
          ^
/usr/include/c++/4.9/bits/stringfwd.h:62:23: error: expected unqualified-id
  typedef basic_string<char>    string;   
                      ^
/usr/include/c++/4.9/bits/stringfwd.h:65:21: error: explicit specialization of non-template struct 'char_traits'
  template<> struct char_traits<wchar_t>;
                    ^          ~~~~~~~~~
/usr/include/c++/4.9/bits/stringfwd.h:68:11: error: unknown type name 'basic_string'
  typedef basic_string<wchar_t> wstring;   
          ^
/usr/include/c++/4.9/bits/stringfwd.h:68:23: error: expected unqualified-id
  typedef basic_string<wchar_t> wstring;   
                      ^
/usr/include/c++/4.9/bits/stringfwd.h:86:1: error: unknown type name '_GLIBCXX_END_NAMESPACE_VERSION'
_GLIBCXX_END_NAMESPACE_VERSION
^
/usr/include/c++/4.9/bits/stringfwd.h:87:1: error: expected unqualified-id
} // namespace std
^
In file included from input_line_3:1:
In file included from /usr/include/c++/4.9/iostream:39:
In file included from /usr/include/c++/4.9/ostream:38:
In file included from /usr/include/c++/4.9/ios:38:
In file included from /usr/include/c++/4.9/iosfwd:40:
In file included from /usr/include/c++/4.9/bits/postypes.h:40:
In file included from /usr/include/c++/4.9/cwchar:44:
In file included from /usr/include/wchar.h:52:
/home/ybochkarev/bin/cling/lib/clang/3.9.0/include/stddef.h:62:9: error: unknown type name '__SIZE_TYPE__'
typedef __SIZE_TYPE__ size_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

My test cpp file is this:
``` cpp
#include <iostream>
using namespace std;

int main()
{
    cout << "Hello World!";
    return 0;
}
```

Specifically, I'm trying to integrate cling jupyter kernel with atom using hydrogen plugin (not sure if it makes any difference regarding this problem but anyway). I Is there a way to make it work? Thank you.

**Comment by karies** [comment]
@balta2ar - we're fixing the compilation error as we speak. I'll let you know.

Ubuntu 12.04 or which Ubuntu are you referring to?

**Comment by balta2ar** [comment]
@karies Thank you! Yes, I'm using Ubuntu 12.04. In fact, it has just occurred to me that my environment allows me to also try Ubuntu 14.04 in docker, so I'll give it go as well.

**Comment by karies** [comment]
Ubuntu 12.04 has an ancient GCC (4.6); I doubt you'll have a lot of fun with it... 14.04 is much better in that respect (GCC 4.8).

The build error is fixed.

Could you open new issues for new issues if possible? ;-)

**Comment by balta2ar** [comment]
Thanks, your fix helped. Well, to some extent. Another error occurred but I think it's because of my ancient, not fun Ubuntu 12.04. Never mind, I've managed to run cling in docker in Ubuntu.

Sorry for abusing this thread, but I have small question which I don't think is worth creating a new issue. If I have a project that compiles with cmake, what's the best way to load all its files in one go into cling and start working on it iteratively? I don't want to load files manually one by one. It's not clear how to do that from documentation and from command-line help...

**Comment by karies** [comment]
You would create a pch, and -include-pch that into cling at startup. See e.g. https://root.cern.ch/gitweb/?p=root.git;a=blob;f=core/meta/src/TCling.cxx;h=38f8feb3ae19ad17cc2adf939000b831570b6c7e;hb=HEAD#l1069 where we do this, too. Works!

**Comment by balta2ar** [comment]
Honestly, I'm not CMake or C++ expert and it would definitely be useful if these steps were documented. Ideally, I'd like to see an example where a project of moderate size that uses CMake is taken as an example, and documentation shows steps needed to adjust its CMake to add precompiled headers, how to load the project into cling and do something simple but useful. That would allow new users of cling to start using it faster and easier.

Do you think the docs could be updated to include something of this kind? Want me to create new issue for that?

**Comment by karies** [comment]
2*yes! And I'd appreciate a PR on that, too ;-) See www/ in cling's repo.
