### ISSUE TITLE
Error using Kernel from prebuilt archive 

### ISSUE THREAD

**Issue by diimdeep** [root-mirror/cling#15]
Installed cling from `https://root.cern.ch/download/cling/cling_2016-05-01_mac1011.tar.bz2` to `~/.local`   
and kernel from `https://root.cern.ch/download/cling/cling_2016-05-01_sources.tar.bz2/src/tools/cling/tools/Jupyter/kernel` with `python3 -m pip install -e .`

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.4

$ jupyter --version
4.1.0
````

Cling works just fine   
Tried to run kernel and got error

```
Warning in cling::IncrementalParser::CheckABICompatibility():
  C++ ABI mismatch, compiled with _LIBCPP_VERSION v1101 running with v3700
input_line_2:1:10: fatal error: 'cling/Interpreter/RuntimeUniverse.h' file not found
#include "cling/Interpreter/RuntimeUniverse.h"
         ^
[ClingKernelApp] ERROR | UNKNOWN MESSAGE TYPE: 'comm_open'
```

**Comment by newlawrence** [comment]
Same exact error here.

**Comment by karies** [comment]
You might need to update your Xcode or run `xcode-select --install`. Does either help?

**Comment by dzosz** [comment]
You have to create a notebook in directory where the includes are. Is it supposed to work like that?
`[tommy@tomek my_empty_dir]$ ln -s ~/cling_binary/include/cling/ cling
[tommy@tomek my_empty_dir]$ jupyter notebook --no-browser
no error`

**Comment by kmbroga** [comment]
Having exactly the same problem.

**Comment by karies** [comment]
@dzosz - re directory: I just retried (and updated the README.md now that the cling kernel is installed) and it just works for me, following the steps from the README.md https://github.com/root-mirror/cling/blob/master/tools/Jupyter/README.md It's key to have cling in the PATH; without that, jupyter won't find anything.

@diimdeep - that was likely because the binary was done with an old Xcode. I believe we have updated it; can you confirm? Else, could you let us know and just try to build cling yourself? It's fairly straight forward.

@kmbroga - which of the problems mentioned above to you have?

**Comment by kmbroga** [comment]
I am getting the following error error:
`fatal error: 'cling/Interpreter/RuntimeUniverse.h' file not found`

I tried adding both of the following to my bashrc file
`export PATH=<install path>/cling_2016-07-25_ubuntu16/bin:$PATH`
and
`export PATH=<install path>/cling_2016-07-25_ubuntu16/include/cling:$PATH`

But neither of them worked. Only if I add symlink to `<install path>/cling_2016-07-25_ubuntu16/include/cling` in the directory from which I launch jupyter notebook, c++ kernel does not crash.

**Comment by karies** [comment]
Thanks, I can reproduce that! Looking into it...

**Comment by karies** [comment]
...and fixed. New binaries are here: http://root.cern/download/cling

Could you confirm, please?

**Comment by dzosz** [comment]
Works good on fedora23.

**Comment by karies** [comment]
Thanks for confirming!

**Comment by diimdeep** [comment]
Works on OSX.

**Comment by karies** [comment]
@diimdeep Excellent, thanks!
