### ISSUE TITLE
github is behind root

### ISSUE THREAD

**Issue by ObiWahn** [root-mirror/cling#2]
It would be nice to have the same version on both servers. I found it confusing to see different code on github and in my docker image.

e.g: lline 84 in the clingkernel.py is today `if not self.libclingJupyter:` which should be something like:  `if not getattr(self,"libclingJupyter",None)` and is something totally different on github (https://github.com/root-mirror/cling/blob/5c750a2c4c7ce02e6c5ba2787a34b9268cb66ae7/tools/Jupyter/kernel/clingkernel.py#L84)

**Comment by karies** [comment]
Now synced automatically.
