### ISSUE TITLE
Auto try catch (feature request)

### ISSUE THREAD

**Issue by catskul** [root-mirror/cling#27]
Having the interpreter exit on an exception, while it makes sense, is very inconvenient when exploring an API, or doign some trial and error work.

It would be nice if there was a way to effectively wrap every line in a try catch block (perhaps with a custom handler, or simply a print out).

**Comment by vgvassilev** [comment]
Could you give us a code example?

**Comment by catskul** [comment]
Hm, it looks like I misinterpreted some crashes in cling itself as exceptions in the code I was trying to run.

I see now that cling does in fact automatically catch exceptions.

I'll see if I can reproduce those other crashes and report them as bugs.

**Comment by catskul** [comment]
Probably crashes related to:

related to warning I'm getting:

Warning in cling::IncrementalParser::CheckABICompatibility():
  C++ ABI mismatch, compiled with __GLIBCXX__ v20160609 running with v20160413

**Comment by vgvassilev** [comment]
Yes this should be fixed with our next release (coming in the next couple of days).
