### ISSUE TITLE
configure flags are not passed down during make

### ISSUE THREAD

**Issue by ObiWahn** [root-mirror/cling#3]
--enable-shared had no effect on cling

**Comment by karies** [comment]
Ack, will tackle that once cling has been shifted to a current llvm revision - I need a recent llvm build system feature for that.

**Comment by marsupial** [comment]
I have a pull request that includes this fix. The specific commit is here: [https://github.com/marsupial/cling/commit/3cd5bd3fc95a3cff62f2779a14896ecd94bf8f60](url)

**Comment by karies** [comment]
That's merged; this should now work. Additionally we can build (and currently always do, although I will make that a CMake option) libcling.so which combines all the cling libraries.
