### ISSUE TITLE
README: cmake commandline incorrect

### ISSUE THREAD

**Issue by ObiWahn** [root-mirror/cling#4]
`-DLLVM_TARGETS_TO_BUILD=CBackend\;CppBackend\;X86 \`
->
```
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:414 (message):
  Unexpected failure executing llvm-build: Usage: llvm-build [options]

  

  llvm-build: error: invalid target to enable: 'CBackend' (not in project)

```

**Comment by dabro** [comment]
I encountered the same problem.

**Comment by punchEnbody** [comment]
Same here. This is on a mac. Is this truly a build option problem or is it the clang compiler (the apple version) causing the trouble?

**Comment by karies** [comment]
Where does `-DLLVM_TARGETS_TO_BUILD=CBackend\;CppBackend\;X86` come from? Are you using the llvm repo and branch as prescribed in the cling build instructions at https://root.cern.ch/cling-build-instructions ?

Axel.

**Comment by punchEnbody** [comment]
cling can been used in the Python jupyter server to interact with cling via a web interface. Apparently the cling kernel for jupyter has been moved to cling itself. The page with the directions I have been following is below, where I got the cmake commands. 

https://github.com/root-mirror/cling#jupyter

It was referenced from here

https://github.com/minrk/clingkernel

Is this off the beaten path somehow?

>>>bill<<<

**Comment by synecdoche** [comment]
I encountered this as well. I was also following the `CMake` instructions from `README.md` (on https://github.com/root-mirror/cling#jupyter).

After some sleuthing, I discovered that there's no `CBackend` target in any of the `LLVMBuild.txt` files. Removing it from `-DLLVM_TARGETS_TO_BUILD` in the `cmake` command let `cmake` finish generating the makefiles.

You may wish to update your `README.md`.

**Comment by karies** [comment]
README.md is finally updated, thanks for pointing this out.
