### ISSUE TITLE
jupyter notebook error (AttributeError: 'ClingKernelApp' object has no attribute 'displayhook')

### ISSUE THREAD

**Issue by akstrfn** [root-mirror/cling#56]
Hi,

While trying to setup Jupyter notebooks with cling I ran into following issue (not the whole traceback):
```
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 373, in init_kernel
    self.displayhook.get_execution_count = lambda: kernel.execution_count
AttributeError: 'ClingKernelApp' object has no attribute 'displayhook'
```
I have tracked down the error to be in the file [clingkernel.py](https://github.com/root-mirror/cling/blob/master/tools/Jupyter/kernel/clingkernel.py) in the method ```init_io``` that is on line [284](https://github.com/root-mirror/cling/blob/master/tools/Jupyter/kernel/clingkernel.py#L284). This method overrides the method from the parent class and due to that it skips the initialisation of the ```displayhook``` attribute. Removing the ```init_io``` method seems to work.

Cheers,
Aleks

**Comment by vgvassilev** [comment]
Does PR #55 solve it for you?

**Comment by akstrfn** [comment]
@vgvassilev of course... Sorry for missing it.

**Comment by vgvassilev** [comment]
No worries, thanks for letting us know. We will merge this soon.
