### ISSUE TITLE
New line after `std::[cout/cerr]` output in the regular cling interpreter

### ISSUE THREAD

**Issue by SylvainCorlay** [root-mirror/cling#61]
When using the regular cling interpreter, printing in the standard output, and not ending with a newline results in something like this:

``` c++
[cling]$ std::cout << "foobar";
foobar[cling]$ 
```

I don't think that one should be required to end with a new line. If we do so, it would result in an empty line in the case of a jupyter notebook or console.

**Comment by pcanal** [comment]
This seems very hard to implement without leading to an empty line on the prompt in many other cases, like:
```
[cling]$ std::cout << "foobar\n";
foobar
[cling]$ 
```
(and of course the 'newline' many actually be printed very indirectly inside a function call).

i.e. why are " jupyter notebook or console" adding a empty line?

**Comment by SylvainCorlay** [comment]
That is right, with my proposal, the logical behavior when you add a newline character `\n` would be to have an empty line in the console.

This is the behavoior in the jupyter console case, even with the cling kernel.

**Comment by SylvainCorlay** [comment]
> [...] without leading to an empty line on the prompt in many other cases

to be clear, I think that it is fine to have an empty line in that case.

**Comment by karies** [comment]
I disagree: no newline means no newline. Neither regular cout tries to inject missing newlines, nor any interpreter that I know of, take e.g. bash, gdb, python. I don't understand what you are trying to achieve, could you maybe give some context?

**Comment by SylvainCorlay** [comment]
> I disagree: no newline means no newline. Neither regular cout tries to inject missing newlines, nor any interpreter that I know of, take e.g. bash, gdb, python. I don't understand what you are trying to achieve, could you maybe give some context?

Sorry if I was not clear.

1. In the above example featuring the the cpython interpreter the behavior is consistent in that there is a clear difference between the case where the string includes a newline or not.

     (If you like, it is equivalent to considering that the first character of the prompt is `\n`...)

2. When running cling as a kernel for the jupyter console or the jupyter notebook, the behavior is the one that I am proposing. So if you add a newline to have a nice behavior in the regular cling interpreter, the same code will have an odd empty line in the case where cling is used as a kernel.

3. I don't understand what you mean regarding the gdb, python or bash interpreters which all behave like what I would like cling to do.

**Comment by karies** [comment]
`std::cout` and `printf` behave the way they do; try it in a compiled binary and you'll see that it really doesn't add a newline. And so neither should cling.

You get the same behavior from python if you use a similar tool:
```
>>> import sys
>>> sys.stdout.write('hi there')
hi there>>> 
```

For display on a web page that's different, and cling's Julyter kernel adds newlines, boxes, what not.
