### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [root-mirror/cling#68]
Is it possible to consider to relicense Cling under a more commercial friendly license like ASL 2.0? Alternatively a license like BSD or MIT.

And also perhaps ROOT is this is an option.

**Comment by karies** [comment]
It's dual licensed; UI/NCSAOSL is one of the options and is extremely similar to MIT.

We have the same license as clang/llvm; we are considering migrating to ASL as llvm/clang does.

ROOT is intentionally licensed as LGPL; we know of many companies using it. I'd call LGPL'ed open source software very commercial friendly!

**Comment by sirinath** [comment]
By bad. When I checked I only noticed LGPL 2.1.

Any way can ROOT be also dual licensed with UI/NCSAOSL

**Comment by karies** [comment]
No, we are not planning on doing that.
