### ISSUE TITLE
jupyter kernel setup broken - must not delete src

### ISSUE THREAD

**Issue by ObiWahn** [root-mirror/cling#7]
A user is not allowed to delete the src directroy after installation. In case he deletes the dir Jubpiter will
refuse to load the cling kernel.

  1 FROM obiwahn/jupyterhub_notebook:latest
  2 
  3 # install packages
  4 RUN apt-get update && \
  5     apt-get install -y vim groff cmake libboost-all-dev && \
  6     apt-get clean
  7 
  8 # build and install cling
  9 RUN cd /srv && \
 10     mkdir cling-build && \
 11     git clone http://root.cern.ch/git/llvm.git cling-src && \
 12     cd /srv/cling-src && \
 13     git checkout cling-patches && \
 14     cd /srv/cling-src/tools && \
 15     git clone https://github.com/ObiWahn/cling.git && \
 16     git clone http://root.cern.ch/git/clang.git && \
 17     cd /srv/cling-src/tools/clang && \
 18     git checkout cling-patches && \
 19     cd /srv/cling-build && \
 20     cmake -DCMAKE_INSTALL_PREFIX=/usr/local \
 21           -DLLVM_TARGETS_TO_BUILD=CppBackend\;X86 \
 22           -DCMAKE_BUILD_TYPE=Debug \
 23           ../cling-src && \
 24     make -j $(nproc) && \
 25     make install && \
 26     cd /srv/cling-src/tools/cling/tools/Jupyter/kernel && \
 27     pip install -e . && \
 28     jupyter kernelspec install cling && \
 29     rm -fr /srv/cling-build
 30 
 31 #    git clone http://root.cern.ch/git/cling.git && \
 32 
 33 # After installing we must not delete the src folder if we 
 34 # want to use cling in jupyter
 35 # && \
 36 #    rm -fr /srv/cling-src

**Comment by karies** [comment]
I agree that this is bad. I'd very much appreciate a patch for this.

**Comment by karies** [comment]
Fixed: the install target now also installs the Jupyter kernel. README.md is adjusted.
